; Copyright 2019 GoneTone
;
; Line Bot
; 範例 Example Bot 配置文件
;
; 此範例 GitHub 專案：https://github.com/GoneTone/line-example-bot-php
; 官方文檔：https://developers.line.biz/en/reference/messaging-api/

[Channel]
; 請在雙引號內輸入您的 Line Bot "Channel access token"
Token = "mBaIGQ01qRFiE1a6noffFx4NAARxjiGapyD1BO/XJNARpOvdi0uADJGlxsDCMh0KG0lVgVxlQhQkJRxk9SCn3/3pIo5uWFCLJCncEPw6NM+CLOoHrA7xL3rrCpP6amSRhJ7oJw+kwvhf3Yq6uowGuwdB04t89/1O/w1cDnyilFU="

; 請在雙引號內輸入您的 Line Bot "Channel secret"
Secret = "
fedc88321a803af40f824c811b3ccee6

"
