name: manual-hexo-build

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run test build (no publish) or deploy?"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - deploy
      lang:
        description: "Which language site?"
        required: true
        default: "zh"
        type: choice
        options:
          - zh
          - en

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.1"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: Select config for chosen lang
        run: |
          cp "config-${{ github.event.inputs.lang }}.yml" _config.yml
          cp "config-butterfly-${{ github.event.inputs.lang }}.yml" "_config.butterfly.yml"
          echo "Using language=${{ github.event.inputs.lang }}"
          echo "Final _config.yml:"
          head -n 40 _config.yml

      # ===== test mode =====
      - name: Generate static site (test mode)
        if: ${{ github.event.inputs.mode == 'test' }}
        run: |
          npx hexo clean
          npx hexo g
          echo "Hexo generate complete."
          ls -al

      - name: Upload preview artifact
        if: ${{ github.event.inputs.mode == 'test' }}
        uses: actions/upload-artifact@v4
        with:
          name: "preview-${{ github.event.inputs.lang }}"
          # zh build goes to public/
          # en build goes to public-en/
          path: ${{ github.event.inputs.lang == 'en' && 'public-en' || 'public' }}
          retention-days: 7

            # ========== deploy mode: zh ==========
      - name: Configure git credential for zh deploy
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'zh' }}
        run: |
          echo "Deploying zh -> same repo branch 'deploy' using GITHUB_TOKEN"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # no extra credential needed as long as deploy.repo uses HTTPS URL
          # and points back to this same repo (leozzmc.github.io.git)

      - name: Build & Deploy zh (hexo deploy)
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'zh' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running zh deploy..."
          npm run kk
          echo "ZH Deploy done."

      - name: Upload deployed zh artifact
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'zh' }}
        uses: actions/upload-artifact@v4
        with:
          name: "deployed-zh"
          path: public
          retention-days: 7

      # ========== deploy mode: en ==========
      - name: Configure git credential for en deploy
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'en' }}
        run: |
          echo "Deploying en -> external repo leozzmc/en using EN_REPO_TOKEN"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git config credential.helper store
          cat > ~/.git-credentials <<EOF
https://${{ secrets.EN_REPO_TOKEN }}:@github.com/leozzmc/en.git
EOF

      - name: Build & Deploy en (hexo deploy)
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'en' }}
        env:
          EN_REPO_TOKEN: ${{ secrets.EN_REPO_TOKEN }}
        run: |
          echo "Running en deploy..."
          npm run kk
          echo "EN Deploy done."

      - name: Upload deployed en artifact
        if: ${{ github.event.inputs.mode == 'deploy' && github.event.inputs.lang == 'en' }}
        uses: actions/upload-artifact@v4
        with:
          name: "deployed-en"
          path: public-en
          retention-days: 7
